language: node_js
node_js:
  - 13

# docker services
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy marait123/reverseproxy
  - docker tag udagram-api-user marait123/udagram-api-user
  - docker tag udagram-api-feed marait123/udagram-api-feed
  - docker tag udagram-frontend marait123/udagram-frontend

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  marait123/reverseproxy
  - docker push  marait123/udagram-api-user
  - docker push  marait123/udagram-api-feed
  - docker push  marait123/udagram-frontend
